CREATE TABLE "users"
(
    "id"              SERIAL PRIMARY KEY NOT NULL,
    "first_name"      varchar(30),
    "last_name"       varchar(30),
    "passport_number" varchar(20),
    "email"           varchar(60),
    login             varchar(20),
    "password"        varchar(20),
    "role"            varchar(20),
    "address"         varchar(70),
    "birth_date"      date,
    "status"          varchar(15),
    "created_at"      timestamp DEFAULT (now())
);

CREATE TABLE "books"
(
    "id"          SERIAL PRIMARY KEY NOT NULL,
    "title"       varchar(60),
    "genre_id"    int,
    "author"      varchar(60),
    "description" varchar(1024),
    "book_copies" int,
    "created_at"  timestamp DEFAULT (now())
);

CREATE TABLE "genres"
(
    "id"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(60)
);

CREATE TABLE "orders"
(
    "id"          SERIAL PRIMARY KEY NOT NULL,
    "user_id"     int,
    "book_id"     int,
    "issue_date"  timestamp,
    "return_date" timestamp,
    "usage_days"  int,
    "type"        varchar(20)
);

CREATE TABLE "order_details"
(
    "id"         SERIAL PRIMARY KEY NOT NULL,
    "order_id"   int,
    "user_id"    int,
    "status"     varchar(20),
    "comment"    varchar(100),
    "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "images"
(
    "id"      SERIAL PRIMARY KEY NOT NULL,
    "book_id" int,
    "url"     varchar(100)
);

ALTER TABLE "genres"
    ADD FOREIGN KEY ("id") REFERENCES "books" ("id");

ALTER TABLE "orders"
    ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "orders"
    ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

ALTER TABLE "order_details"
    ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_details"
    ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "images"
    ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

COMMIT;